### ISSUE TITLE
Add release checklist templates

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cuda-python#322]
Release managers need to go through this check list and ensure all tasks are done

- [ ] Is this release for `cuda-bindings`?
   - **TODO**
- [ ] Is this release for `cuda-core`?
   - [ ] File an internal nvbug to communicate test plan & release schedule with QA
   - [ ] Ensure all pending PRs are reviewed, tested, and merged
   - [ ] Create a public rc tag
   - [ ] Point QA to fetch public artifacts (wheels) from the GHA run ID, example:
   ```shell
   gh run download 12323257563 -p "cuda-core*" -R NVIDIA/cuda-python
   ```
   - [ ] Wait for QA reports and fix any issues found
   - [ ] Finalize the doc update
   - [ ] Rebuild the docs
   - [ ] Create a public release tag
      - [ ] If any code change happens, rebuild the wheels from the new tag
   - [ ] Upload wheels to PyPI
   - [ ] Finalize the announcement update
   - [ ] Send out the announcement
      - [ ] Internally
      - [ ] Externally (GitHub Release -> Announcement)
   - [ ] Update the conda recipe & release conda packages
   - [ ] Post-release QA
